Repository DIT112-V21/group-01, pull requests merged in 2021-05, with the labels that each got.

#56 Develop
  .gitignore
  .idea/runConfigurations.xml
  README.md
  arduino/smartcar/smartcar.ino
  client/app/build.gradle
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/group01/smartcar/client/CarControl.java
  client/app/src/main/java/group01/smartcar/client/DrivingScreen.java
  client/app/src/main/java/group01/smartcar/client/JoystickView.java
  client/app/src/main/java/group01/smartcar/client/MainActivity.java
  client/app/src/main/java/group01/smartcar/client/SmartCar.java
  client/app/src/main/java/group01/smartcar/client/SmartCarApplication.java
  client/app/src/main/java/group01/smartcar/client/SmartCarVoiceControl.java
  client/app/src/main/java/group01/smartcar/client/Speedometer.java
  client/app/src/main/java/group01/smartcar/client/Status.java
  client/app/src/main/java/group01/smartcar/client/UserMenuActivity.java
  client/app/src/main/java/group01/smartcar/client/activity/DrivingActivity.java
  client/app/src/main/java/group01/smartcar/client/activity/LoginActivity.java
  client/app/src/main/java/group01/smartcar/client/activity/UserMenuActivity.java
  client/app/src/main/java/group01/smartcar/client/async/TaskExecutor.java
  client/app/src/main/java/group01/smartcar/client/internal/InternalSmartCar.java
  client/app/src/main/java/group01/smartcar/client/internal/InternalSmartCarVoiceControl.java
  client/app/src/main/java/group01/smartcar/client/internal/mqtt/SmartCarTopics.java
  client/app/src/main/java/group01/smartcar/client/internal/resources/Secrets.java
  client/app/src/main/java/group01/smartcar/client/internal/speech/VoiceControlCommand.java
  client/app/src/main/java/group01/smartcar/client/internal/speech/commands/ForwardCommand.java
  client/app/src/main/java/group01/smartcar/client/internal/speech/commands/ReverseCommand.java
  client/app/src/main/java/group01/smartcar/client/internal/speech/commands/SpeedCommand.java
  client/app/src/main/java/group01/smartcar/client/internal/speech/commands/StopCommand.java
  client/app/src/main/java/group01/smartcar/client/internal/speech/commands/TurnCommand.java
  client/app/src/main/java/group01/smartcar/client/mqtt/MqttClient.java
  client/app/src/main/java/group01/smartcar/client/speech/SpeechListener.java
  client/app/src/main/java/group01/smartcar/client/view/ProximityIndicator.java
  client/app/src/main/java/group01/smartcar/client/view/Speedometer.java
  client/app/src/main/res/back.svg
  client/app/src/main/res/button.svg
  client/app/src/main/res/drawable/ic_back.xml
  client/app/src/main/res/drawable/ic_button.xml
  client/app/src/main/res/drawable/ic_dashboard.xml
  client/app/src/main/res/drawable/ic_exit_button.xml
  client/app/src/main/res/drawable/ic_gauge.xml
  client/app/src/main/res/drawable/ic_gauge_gradient.xml
  client/app/src/main/res/drawable/ic_gauge_left.xml
  client/app/src/main/res/drawable/ic_gauge_left_indicator.xml
  client/app/src/main/res/drawable/ic_gauge_right.xml
  client/app/src/main/res/drawable/ic_gauge_right_indicator.xml
  client/app/src/main/res/drawable/ic_knob.xml
  client/app/src/main/res/drawable/ic_mic.xml
  client/app/src/main/res/drawable/ic_mic_active.xml
  client/app/src/main/res/drawable/ic_proximity_car.xml
  client/app/src/main/res/drawable/ic_switch_thumb.xml
  client/app/src/main/res/drawable/ic_switch_thumb_active.xml
  client/app/src/main/res/drawable/ic_switch_track.xml
  client/app/src/main/res/drawable/ic_switch_track_active.xml
  client/app/src/main/res/layout/activity_drive.xml
  client/app/src/main/res/layout/activity_main.xml
  client/app/src/main/res/layout/activity_usermenu.xml
  client/app/src/main/res/values/colors.xml
  client/secrets-default.properties
Labels: enhancement

#66 Park drive animation
  client/app/src/main/java/group01/smartcar/client/activity/DrivingActivity.java
  client/app/src/main/java/group01/smartcar/client/view/ProximityIndicator.java
  client/app/src/main/res/drawable/speedometer_overlay.xml
  client/app/src/main/res/layout/activity_drive.xml
Labels: enhancement

#67 Unit tests
  client/app/build.gradle
  client/app/src/androidTest/java/group01/smartcar/client/activity/DrivingActivityTest.java
  client/app/src/androidTest/java/group01/smartcar/client/activity/LoginActivityTest.java
  client/app/src/main/java/group01/smartcar/client/internal/resources/Secrets.java
  client/secrets-default.properties
Labels: enhancement, sprint#4

#75 Fix unit test ci failure
  .github/workflows/android-build.yml
  client/app/src/androidTest/java/group01/smartcar/client/activity/DrivingActivityTest.java
  client/app/src/main/java/group01/smartcar/client/internal/InternalSmartCar.java
Labels: bug
